name: Get Hash

on:
  schedule:
    - cron: '0 * * * *' 

jobs:
  auto_commit_hash:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Set up Git
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Action"
          git config --global credential.helper store
          echo "machine github.com login ${{ secrets.GH_USERNAME }} password ${{ secrets.GH_TOKEN }}" > ~/.git-credentials

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install beautifulsoup4 requests

      - name: Run Python script
        run: |
          python hash.py  

      - name: Commit and push changes
        run: |
          git add hash.json
          git commit -m "UPDATE [HASH.JSON]"
          git push
