name: Status

on:
  schedule:
    - cron: '0 0 * * *'  
  workflow_dispatch:
  push: {branches: ["master", "main"]}      
jobs:
  check-api:
    runs-on: ubuntu-latest
    steps:
      - name: Status
        run: |
          curl -X POST https://fullbots.vercel.app/up/status \
          -H "X-API-Key: ${{ secrets.API_KEY }}" \
          -H "Content-Type: application/json" 
